name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release (eg. v0.1.2)'
        required: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v3
        with:
          # This action defaults to only getting the latest commit. Setting to 0 makes it retrieve the full git commit history
          fetch-depth: '0'
      - run: |
          git config --global user.email "ci@deephaven.io"
          git config --global user.name "GitHub CI"
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Get changelog
        # Get the changelog and write it out to a file so it can be used by the create-release step later
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: npx lerna-changelog --next-version=${{ github.event.inputs.version }} > /tmp/changelog.md
      - name: Version bump
        # lerna version will bump the version, tag it, and push
        run: npx lerna version ${{ github.event.inputs.version }} --yes
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # With a tag_name specified, it creates a release pointing to that commit
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body_path: /tmp/changelog.md
